"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("reflect-metadata");
const discord_js_1 = require("discord.js");
const bot_1 = require("./bot");
const inversify_1 = require("inversify");
const types_1 = require("./types");
const commandRouter_1 = require("./services/commandRouter/commandRouter");
const messageSender_1 = require("./services/messageSender/messageSender");
const pingResponder_1 = require("./services/pingResponder/pingResponder");
const messageRemover_1 = require("./services/messageRemover/messageRemover");
let container = new inversify_1.Container();
container.bind(types_1.TYPES.Bot).to(bot_1.Bot).inSingletonScope();
container.bind(types_1.TYPES.Client).toConstantValue(new discord_js_1.Client());
container.bind(types_1.TYPES.Token).toConstantValue(process.env.TOKEN);
container.bind(types_1.TYPES.CommandRouter).to(commandRouter_1.CommandRouter).inSingletonScope();
container.bind(types_1.TYPES.MessageSender).to(messageSender_1.MessageSender).inSingletonScope();
container.bind(types_1.TYPES.PingResponder).to(pingResponder_1.PingResponder).inSingletonScope();
container.bind(types_1.TYPES.MessageRemover).to(messageRemover_1.MessageRemover).inSingletonScope();
exports.default = container;
//# sourceMappingURL=inversify.config.js.map